import type {
  AircraftId,
  AircraftSpec,
  FlightSetup,
  Livery,
  WeatherId,
  WeatherSpec,
} from "./types";

export const AIRCRAFT: Record<AircraftId, AircraftSpec> = {
  cessna: {
    id: "cessna",
    shortName: "C172",
    manufacturer: "Cessna",
    fullName: "Cessna 172 Skyhawk",
    category: "Single-engine trainer",
    tagline: "Forgiving handling. Unfiltered flying.",
    seats: 4,
    massKg: 1_050,
    wingArea: 16.2,
    spanM: 11,
    lengthM: 8.3,
    heightM: 2.7,
    gearHeightM: 1.05,
    maxThrustN: 2_200,
    engineCount: 1,
    engineKind: "piston",
    spoolSeconds: 0.35,
    cl0: 0.28,
    clAlpha: 4.8,
    clMax: 1.45,
    cd0: 0.032,
    inducedDrag: 0.055,
    rotateKts: 55,
    approachKts: 65,
    cruiseKts: 122,
    maxKts: 163,
    ceilingFt: 14_000,
    rangeNm: 640,
    flapLift: 0.55,
    flapDrag: 0.065,
    gearDrag: 0,
    controlPower: 1,
    pitchResponse: 1.55,
    rollResponse: 1.8,
    yawResponse: 1.2,
    maxSafeSinkMps: 3,
    hardLandingMps: 6,
    cockpitPosition: [-0.38, 0.62, -1.65],
    cameraFov: 72,
  },
  learjet: {
    id: "learjet",
    shortName: "LJ45",
    manufacturer: "Bombardier",
    fullName: "Learjet 45",
    category: "Light business jet",
    tagline: "Fast, precise, and built to climb.",
    seats: 9,
    massKg: 8_000,
    wingArea: 29,
    spanM: 14.6,
    lengthM: 17.7,
    heightM: 4.3,
    gearHeightM: 1.7,
    maxThrustN: 31_200,
    engineCount: 2,
    engineKind: "turbofan",
    spoolSeconds: 2,
    cl0: 0.22,
    clAlpha: 5,
    clMax: 1.35,
    cd0: 0.022,
    inducedDrag: 0.045,
    rotateKts: 111,
    approachKts: 115,
    cruiseKts: 465,
    maxKts: 510,
    ceilingFt: 51_000,
    rangeNm: 1_824,
    flapLift: 0.7,
    flapDrag: 0.09,
    gearDrag: 0.02,
    controlPower: 0.88,
    pitchResponse: 1.1,
    rollResponse: 1.25,
    yawResponse: 0.8,
    maxSafeSinkMps: 2.5,
    hardLandingMps: 5,
    cockpitPosition: [-0.48, 1.05, -5.55],
    cameraFov: 69,
  },
  max9: {
    id: "max9",
    shortName: "B39M",
    manufacturer: "Boeing",
    fullName: "737 MAX 9",
    category: "Narrow-body airliner",
    tagline: "Command the line from a full glass flight deck.",
    seats: 220,
    massKg: 72_000,
    wingArea: 127,
    spanM: 35.9,
    lengthM: 42.2,
    heightM: 12.3,
    gearHeightM: 3,
    maxThrustN: 250_000,
    engineCount: 2,
    engineKind: "turbofan",
    spoolSeconds: 4,
    cl0: 0.21,
    clAlpha: 5.2,
    clMax: 1.45,
    cd0: 0.02,
    inducedDrag: 0.042,
    rotateKts: 148,
    approachKts: 150,
    cruiseKts: 453,
    maxKts: 544,
    ceilingFt: 41_000,
    rangeNm: 3_300,
    flapLift: 0.95,
    flapDrag: 0.11,
    gearDrag: 0.018,
    controlPower: 0.68,
    pitchResponse: 0.72,
    rollResponse: 0.72,
    yawResponse: 0.48,
    maxSafeSinkMps: 2.2,
    hardLandingMps: 4.5,
    cockpitPosition: [-0.62, 1.85, -15.2],
    cameraFov: 66,
  },
};

export const WEATHER: Record<WeatherId, WeatherSpec> = {
  clear: {
    id: "clear",
    label: "Clear",
    description: "CAVOK · light westerly",
    windKts: 5,
    windDirectionDeg: 270,
    gustKts: 1,
    visibilityM: 45_000,
    cloudCover: 0.12,
    rain: 0,
    turbulence: 0.04,
    runwayFriction: 0.78,
    skyTop: 0x1765a7,
    skyHorizon: 0xaad8ee,
    fogColor: 0xb8d9e8,
  },
  golden: {
    id: "golden",
    label: "Golden hour",
    description: "Long shadows · calm air",
    windKts: 3,
    windDirectionDeg: 245,
    gustKts: 1,
    visibilityM: 35_000,
    cloudCover: 0.28,
    rain: 0,
    turbulence: 0.03,
    runwayFriction: 0.76,
    skyTop: 0x315a9b,
    skyHorizon: 0xffaa66,
    fogColor: 0xe6a776,
  },
  overcast: {
    id: "overcast",
    label: "Crosswind",
    description: "Broken cloud · gusting 18 kt",
    windKts: 12,
    windDirectionDeg: 285,
    gustKts: 6,
    visibilityM: 16_000,
    cloudCover: 0.74,
    rain: 0.08,
    turbulence: 0.25,
    runwayFriction: 0.63,
    skyTop: 0x50677e,
    skyHorizon: 0xaeb8bd,
    fogColor: 0x9eabb0,
  },
  storm: {
    id: "storm",
    label: "Storm cell",
    description: "Heavy rain · severe gusts",
    windKts: 20,
    windDirectionDeg: 305,
    gustKts: 14,
    visibilityM: 6_000,
    cloudCover: 1,
    rain: 1,
    turbulence: 0.62,
    runwayFriction: 0.43,
    skyTop: 0x111a2a,
    skyHorizon: 0x46505b,
    fogColor: 0x3f4a54,
  },
};

export const LIVERIES: Livery[] = [
  { name: "Aurora", primary: "#eef5f7", accent: "#20d6c7", metallic: 0.72 },
  { name: "Midnight", primary: "#172239", accent: "#f2a93b", metallic: 0.82 },
  { name: "Cardinal", primary: "#f4f1eb", accent: "#e44753", metallic: 0.68 },
  { name: "Pacific", primary: "#dce9f2", accent: "#3f72f2", metallic: 0.77 },
  { name: "Executive", primary: "#20242b", accent: "#d7c59e", metallic: 0.9 },
];

export const DEFAULT_SETUP: FlightSetup = {
  aircraftId: "cessna",
  weatherId: "clear",
  timeId: "day",
  quality: "auto",
  liveryIndex: 0,
  callsign: "AER 271",
  fuelPercent: 72,
  payloadPercent: 54,
  assisted: true,
  tutorial: true,
  readyToTaxi: false,
};

export const AIRPORT = {
  name: "Aurelia International",
  icao: "KAUR",
  elevationFt: 318,
  runway: "36L",
  runwayHeading: 0,
  runwayLengthM: 3_600,
  runwayWidthM: 60,
  gate: "C12",
  towerFrequency: "118.725",
  groundFrequency: "121.900",
};

export const STORAGE_KEY = "aerovia-flight-setup-v1";
